[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "about"
    name = "About me"
    url = "/about"
    weight = 2

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 3

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 4

[[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 5


# Social Media Configuration

[[social]]
    identifier = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/mananjadhav/"
    weight = 1

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/mananjadhav"
    weight = 3

[[social]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 4