# Homepage Config
isSinglePage = true

# Meta Config
description = "Howdy, I am Manan. I am experienced technologist with a knack of solving problems! I help startups build products, teams and technology landscape."

# Header Configuration
avatar = "img/mj-display-picture.jpg"

# disqus is a comment system. see https://disqus.com
disqusShortname = ""

[emoji]
enableEmoji = true

# giscus is a comment system based on GitHub Discussions. see https://giscus.app
[giscus]       
    enable = false
    repo = ""
    repoId = ""
    category = "Announcements"
    categoryId = ""
    # mapping = "pathname"  # comment value is the default value
    # strict = 0
    # reactionsEnabled = 1
    # emitMetadata = 0
    # inputPosition = "top"
    # theme = "light"
    # lang = "zh-CN"
    # lazyLoading = true